export const ME_CLINICS_REQUEST = 'ME_CLINICS_REQUEST'
export const ME_CLINICS_SUCCESS = 'ME_CLINICS_SUCCESS'
export const ME_CLINICS_ERROR = 'ME_CLINICS_ERROR'
export const ME_JOBS_REQUEST = 'ME_JOBS_REQUEST'